SELECT TrackId, Name, Composer FROM Track ORDER BY Composer ASC LIMIT 5 OFFSET 0;
SELECT GenreId, Name FROM Genre ORDER BY NAME ASC;
SELECT GenreId, Name FROM Genre ORDER BY GenreId DESC LIMIT 2;
SELECT Name FROM Genre ASC LIMIT -2 OFFSET 0;